# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright René Ferdinand Rivera Morell 2019-2021.

trigger:
  branches:
    include:
      - develop
      - master
      - feature/*
  paths:
    exclude:
      - .circleci/*
      - .cirrus.yml
      - .drone.star
      - .github/workflows/*
      - .semaphore/*
      - .travis.yml
      - appveyor.yml
      - README.*
pr:
  branches:
    include:
      - develop

variables:
  - { name: co_options, value: "--name container" }

resources:
  containers:
    - {
        container: ubuntu_2404,
        image: "ubuntu:24.04",
        options: "${{variables.co_options}}",
      }
    - {
        container: ubuntu_2204,
        image: "ubuntu:22.04",
        options: "${{variables.co_options}}",
      }
    - {
        container: ubuntu_1804,
        image: "ubuntu:18.04",
        options: "${{variables.co_options}}",
        volumes: [ "/node20217:/node20217:rw,rshared", "/node20217:/__e/node20:ro,rshared" ],
      }
    - {
        container: ubuntu_1604,
        image: "ubuntu:16.04",
        options: "${{variables.co_options}}",
        volumes: [ "/node20217:/node20217:rw,rshared", "/node20217:/__e/node20:ro,rshared" ],
      }
    - {
        container: linux_gcc16,
        image: "teeks99/gcc-ubuntu:16",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc15,
        image: "teeks99/gcc-ubuntu:15",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc14,
        image: "teeks99/gcc-ubuntu:14",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc13,
        image: "teeks99/gcc-ubuntu:13",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc12,
        image: "teeks99/gcc-ubuntu:12",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc11,
        image: "teeks99/gcc-ubuntu:11",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc10,
        image: "teeks99/gcc-ubuntu:10",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc9,
        image: "teeks99/gcc-ubuntu:9",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc8,
        image: "teeks99/gcc-ubuntu:8",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc7,
        image: "teeks99/gcc-ubuntu:7",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc6,
        image: "teeks99/gcc-ubuntu:6",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc5,
        image: "teeks99/gcc-ubuntu:5",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc49,
        image: "teeks99/gcc-ubuntu:4.9",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_gcc48,
        image: "teeks99/gcc-ubuntu:4.8",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang23,
        image: "teeks99/clang-ubuntu:23",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang22,
        image: "teeks99/clang-ubuntu:22",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang21,
        image: "teeks99/clang-ubuntu:21",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang20,
        image: "teeks99/clang-ubuntu:20",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang19,
        image: "teeks99/clang-ubuntu:19",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang18,
        image: "teeks99/clang-ubuntu:18",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang17,
        image: "teeks99/clang-ubuntu:17",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang16,
        image: "teeks99/clang-ubuntu:16",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang15,
        image: "teeks99/clang-ubuntu:15",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang14,
        image: "teeks99/clang-ubuntu:14",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang13,
        image: "teeks99/clang-ubuntu:13",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang12,
        image: "teeks99/clang-ubuntu:12",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang11,
        image: "teeks99/clang-ubuntu:11",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang10,
        image: "teeks99/clang-ubuntu:10",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang9,
        image: "teeks99/clang-ubuntu:9",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang8,
        image: "teeks99/clang-ubuntu:8",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang7,
        image: "teeks99/clang-ubuntu:7",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang6,
        image: "teeks99/clang-ubuntu:6",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang5,
        image: "teeks99/clang-ubuntu:5",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang4,
        image: "teeks99/clang-ubuntu:4",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang39,
        image: "teeks99/clang-ubuntu:3.9",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang38,
        image: "teeks99/clang-ubuntu:3.8",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang37,
        image: "teeks99/clang-ubuntu:3.7",
        options: "${{variables.co_options}}",
      }
    - {
        container: linux_clang36,
        image: "teeks99/clang-ubuntu:3.6",
        options: "${{variables.co_options}}",
      }

stages:
  - template: "tools/ci/azp-linux.yml"
    parameters:
      name: Core
      toolsets:
        - "gcc-16"
      test_steps:
        - bash: |
            set -e
            pushd test
            b2 --verbose-test "--user-config=${HOME}/user-config.jam" -a ${TOOLSET:+toolset=$TOOLSET} ${B2_ARGS} predef-info
            b2 --debug-configuration "--user-config=${HOME}/user-config.jam" -a ${TOOLSET:+toolset=$TOOLSET} ${B2_ARGS} predef predef-headers
            popd
          env:
            B2_ARGS: "cxxstd=03,11,14,17,20,23 cxxstd-dialect=gnu"
          displayName: GNU
        - bash: |
            set -e
            pushd test
            b2 --verbose-test "--user-config=${HOME}/user-config.jam" -a ${TOOLSET:+toolset=$TOOLSET} ${B2_ARGS} predef-info
            b2 --debug-configuration "--user-config=${HOME}/user-config.jam" -a ${TOOLSET:+toolset=$TOOLSET} ${B2_ARGS} predef predef-headers
            popd
          env:
            B2_ARGS: "cxxstd=03,11,14,17,20,23 cxxstd-dialect=iso"
          displayName: ISO
        - bash: |
            set -e
            pushd test
            b2 --verbose-test "--user-config=${HOME}/user-config.jam" -a ${TOOLSET:+toolset=$TOOLSET} ${B2_ARGS} predef-info
            b2 --debug-configuration "--user-config=${HOME}/user-config.jam" -a ${TOOLSET:+toolset=$TOOLSET} ${B2_ARGS} predef predef-headers
            popd
          env:
            B2_ARGS: "cxxstd=03,11,14,17,20,23 cxxstd-dialect=iso warnings=pedantic
              warnings-as-errors=on cxxflags=-Woverloaded-virtual
              cxxflags=-Wshadow cxxflags=-Wnon-virtual-dtor
              cxxflags=-Wzero-as-null-pointer-constant cxxflags=-Wsign-promo
              cxxflags=-Wsign-compare cxxflags=-Wsign-conversion
              cxxflags=-Wundef"
          displayName: Warnings

  - template: "tools/ci/azp-linux.yml"
    parameters:
      name: Compilers
      depends_on: [ "Core" ]
      test_steps:
        - bash: |
            set -e
            pushd test
            b2 --verbose-test "--user-config=${HOME}/user-config.jam" -a ${TOOLSET:+toolset=$TOOLSET} ${B2_ARGS} predef-info
            b2 --debug-configuration "--user-config=${HOME}/user-config.jam" -a ${TOOLSET:+toolset=$TOOLSET} ${B2_ARGS} predef predef-headers
            popd
          displayName: Test

  - stage: Test
    dependsOn: [ "Core" ]
    jobs:
      - job: "macOS"
        strategy:
          matrix:
            Xcode 26.0.1:
              {
                TOOLSET: clang,
                CXX: clang++,
                XCODE_APP: /Applications/Xcode_26.0.1.app,
                VM_IMAGE: "macOS-15",
              }
            Xcode 16.4:
              {
                TOOLSET: clang,
                CXX: clang++,
                XCODE_APP: /Applications/Xcode_16.4.app,
                VM_IMAGE: "macOS-15",
              }
            Xcode 15.4:
              {
                TOOLSET: clang,
                CXX: clang++,
                XCODE_APP: /Applications/Xcode_15.4.app,
                VM_IMAGE: "macOS-14",
              }
        pool:
          vmImage: $(VM_IMAGE)
        steps:
          - bash: |
              set -e
              uname -a
              sudo xcode-select -switch ${XCODE_APP}
              which clang++
              clang++ --version
            displayName: "Install CXX"
          - bash: |
              set -e
              pushd ${HOME}
              wget -nv https://github.com/bfgroup/b2/archive/release.tar.gz
              tar -zxf release.tar.gz
              cd b2-release
              CXX= ./bootstrap.sh
              sudo ./b2 install
              popd
            displayName: "Install B2"
          - bash: |
              set -e
              CXX_PATH=`which ${CXX}`
              echo "using ${TOOLSET} : : ${CXX_PATH} ;" > ${HOME}/user-config.jam
              pushd test
              b2 --verbose-test -a toolset=${TOOLSET} ${B2_ARGS} predef-info
              b2 --debug-configuration -a toolset=${TOOLSET} ${B2_ARGS} predef predef-headers
              popd
            displayName: Test
      - job: "Windows"
        strategy:
          matrix:
            VS 2025:
              TOOLSET: msvc
              TOOLSET_VERSION: 14.5
              B2_ARGS: address-model=32,64 cxxstd=14,latest
              VM_IMAGE: "windows-2025-vs2026"
            VS 2025 (UWP DESKTOP):
              TOOLSET: msvc
              TOOLSET_VERSION: 14.5
              B2_ARGS: address-model=64 define=_WIN32_WINNT=0x0A00
                define=WINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP
              VM_IMAGE: "windows-2025-vs2026"
            VS 2025 (UWP PHONE):
              TOOLSET: msvc
              TOOLSET_VERSION: 14.5
              B2_ARGS: address-model=64 define=_WIN32_WINNT=0x0A00
                define=WINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP
              VM_IMAGE: "windows-2025-vs2026"
            VS 2025 (UWP STORE):
              TOOLSET: msvc
              TOOLSET_VERSION: 14.5
              B2_ARGS: address-model=64 define=_WIN32_WINNT=0x0A00
                define=WINAPI_FAMILY=WINAPI_FAMILY_PC_APP
              VM_IMAGE: "windows-2025-vs2026"
            VS 2025 (UWP SERVER):
              TOOLSET: msvc
              TOOLSET_VERSION: 14.5
              B2_ARGS: address-model=64 define=_WIN32_WINNT=0x0A00
                define=WINAPI_FAMILY=WINAPI_FAMILY_SERVER
              VM_IMAGE: "windows-2025-vs2026"
            VS 2025 (UWP SYSTEM):
              TOOLSET: msvc
              TOOLSET_VERSION: 14.5
              B2_ARGS: address-model=64 define=_WIN32_WINNT=0x0A00
                define=WINAPI_FAMILY=WINAPI_FAMILY_SYSTEM
              VM_IMAGE: "windows-2025-vs2026"
            VS 2022:
              TOOLSET: msvc
              TOOLSET_VERSION: 14.3
              VM_IMAGE: "windows-2022"
            # MinGW 8.1.0:
            #   TOOLSET: gcc
            #   VM_IMAGE: 'windows-2019'
            # MinGW 8.1.0 (UWP DESKTOP):
            #   TOOLSET: gcc
            #   B2_ARGS: define=_WIN32_WINNT=0x0A00 define=WINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP
            #   VM_IMAGE: 'windows-2019'
            # MinGW 8.1.0 (UWP STORE):
            #   TOOLSET: gcc
            #   B2_ARGS: define=_WIN32_WINNT=0x0A00 define=WINAPI_FAMILY=WINAPI_FAMILY_PC_APP
            #   VM_IMAGE: 'windows-2019'
        pool:
          vmImage: $(VM_IMAGE)
        steps:
          - script: |
              cd %BUILD_SOURCESDIRECTORY%/..
              curl "https://github.com/bfgroup/b2/archive/release.zip" -L -o b2.zip
            displayName: Download B2
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: $(Build.SourcesDirectory)/../b2.zip
              destinationFolder: $(Build.SourcesDirectory)/..
              cleanDestinationFolder: false
            displayName: Extract B2
          - script: |
              echo using %TOOLSET% ^: %TOOLSET_VERSION% ^; > %HOMEDRIVE%%HOMEPATH%/user-config.jam
              cd %BUILD_SOURCESDIRECTORY%/../b2-release
              cmd.exe /c bootstrap.bat
            displayName: Install B2
          - script: |
              set BOOST_BUILD_PATH=%BUILD_SOURCESDIRECTORY%/../b2-release
              cd %BUILD_SOURCESDIRECTORY%/test
              %BUILD_SOURCESDIRECTORY%/../b2-release/b2.exe --verbose-test -a toolset=%TOOLSET% %B2_ARGS% predef-info
              %BUILD_SOURCESDIRECTORY%/../b2-release/b2.exe --debug-configuration -a toolset=%TOOLSET% %B2_ARGS% predef predef-headers
            displayName: Test

  # - stage: Extra
  #   dependsOn: [ Test ]
  #   jobs:
  #     - job: "Linux"
  #       strategy:
  #         matrix:
  #           TinyCC:
  #             {
  #               EXE: tcc,
  #               PACKAGES: tcc,
  #               VM_IMAGE: "ubuntu-latest",
  #               TOOLSET: cc,
  #               VERSION: "tcc~0.9.27",
  #               B2_CONFIG: "<cflags>\"-std=c11\" <-soname>-soname",
  #               B2_ARGS: "c",
  #             }
  #       pool:
  #         vmImage: $(VM_IMAGE)
  #       continueOnError: "true"
  #       steps:
  #         - bash: |
  #             set -e
  #             uname -a
  #             ./tools/ci/linux-cxx-install.sh
  #           displayName: "Install CXX"
  #         - bash: |
  #             set -e
  #             pushd ${HOME}
  #             wget -nv https://github.com/bfgroup/b2/archive/main.tar.gz
  #             tar -zxf main.tar.gz
  #             cd b2-main
  #             ./bootstrap.sh
  #             sudo ./b2 install
  #             popd
  #           displayName: "Install B2"
  #         - bash: |
  #             set -e
  #             EXE_PATH=`which ${EXE}`
  #             echo "using ${TOOLSET} : ${VERSION} : ${EXE_PATH} : ${B2_CONFIG} ;" > ${HOME}/user-config.jam
  #             pushd test
  #             b2 --verbose-test -a toolset=${TOOLSET} ${B2_ARGS}
  #             b2 --debug-configuration -a toolset=${TOOLSET} ${B2_ARGS}
  #             popd
  #           displayName: Test

  - stage: WebsiteUpdate
    displayName: "Website Update"
    dependsOn: [ Core, Compilers, Test ]
    condition: and(in(variables['Build.SourceBranch'], 'refs/heads/master',
      'refs/heads/develop'), eq(variables['Build.Repository.Name'],
      'grafikrobot/hash-predef'))
    jobs:

      - job: Documentation
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UseRubyVersion@0
          - bash: |
              gem install asciidoctor
              gem install rouge
            displayName: "Install Doc Tools"
          - bash: |
              set -e
              pushd ${HOME}
              wget -nv https://github.com/bfgroup/b2/archive/release.tar.gz
              tar -zxf release.tar.gz
              cd b2-release
              CXX= ./bootstrap.sh
              sudo ./b2 install
              popd
            displayName: "Install B2"
          - bash: |
              rm -rf ${WEB_DIR}
              git clone --verbose --branch gh-pages --depth 1 "https://${GH_TOKEN}github.com/grafikrobot/hash-predef.git" ${WEB_DIR} || exit 1
              pushd ${WEB_DIR}
              git rm --ignore-unmatch -r "${DOC_DIR}" || exit 1
              mkdir -p "${DOC_DIR}" || exit 1
              popd
            displayName: "Clone Website"
            env:
              GH_TOKEN: $(GitHubToken)
              WEB_DIR: website
              DOC_DIR: manual/$(Build.SourceBranchName)
          - bash: |
              echo "using asciidoctor ;" > ${HOME}/user-config.jam
              pushd doc
              b2 --doc-dir=${WEB_DIR}/${DOC_DIR} html
              git config user.email "doc-bot"
              git config user.name "doc-bot"
              cd ${WEB_DIR}/${DOC_DIR}
              git add --verbose . || exit 1
              git commit -m "Update documentation."
              git push
              popd
            displayName: "Build & Publish"
            env:
              GH_TOKEN: $(GitHubToken)
              WEB_DIR: website
              DOC_DIR: manual/$(Build.SourceBranchName)
