parameters:
  - name: name
    type: string
    default: ""
  - name: apt_packages
    type: string
    default: ""
  - name: depends_on
    type: object
    default: []
  - name: toolsets
    type: object
    default:
      - "gcc-16"
      - "gcc-15"
      - "gcc-14"
      - "gcc-13"
      - "gcc-12"
      - "gcc-11"
      - "gcc-9"
      - "gcc-8"
      - "gcc-7"
      - "gcc-6"
      - "gcc-5"
      - "gcc-4.9"
      - "gcc-4.8"
      - "clang-23"
      - "clang-22"
      - "clang-21"
      - "clang-20"
      - "clang-19"
      - "clang-18"
      - "clang-17"
      - "clang-16"
      - "clang-15"
      - "clang-14"
      - "clang-13"
      - "clang-12"
      - "clang-11"
      - "clang-10"
      - "clang-9"
      - "clang-8"
      - "clang-7"
      - "clang-6"
      - "clang-5"
      - "clang-4"
      - "clang-3.9"
      - "clang-darwin-26.0"
      - "clang-darwin-16.4"
      - "clang-darwin-15."
      - "msvc-14.5"
      - "msvc-14.3"
  - name: b2_tests
    type: object
    default: []

stages:
  - stage: "${{ parameters.name }}"
    dependsOn: ${{ parameters.depends_on }}
    jobs:
      - job: "Linux"
        strategy:
          matrix:
            ${{ if containsValue( parameters.toolsets, 'gcc-16' ) }}:
              GCC 16: { CXX: g++-16, TOOLSET: gcc-16, CONTAINER: "linux_gcc16" }
            ${{ if containsValue( parameters.toolsets, 'gcc-15' ) }}:
              GCC 15: { CXX: g++-15, TOOLSET: gcc-15, CONTAINER: "linux_gcc15" }
            ${{ if containsValue( parameters.toolsets, 'gcc-14' ) }}:
              GCC 14: { CXX: g++-14, TOOLSET: gcc-14, CONTAINER: "linux_gcc14" }
            ${{ if containsValue( parameters.toolsets, 'gcc-13' ) }}:
              GCC 13: { CXX: g++-13, TOOLSET: gcc-13, CONTAINER: "linux_gcc13" }
            ${{ if containsValue( parameters.toolsets, 'gcc-12' ) }}:
              GCC 12: { CXX: g++-12, TOOLSET: gcc-12, CONTAINER: "linux_gcc12" }
            ${{ if containsValue( parameters.toolsets, 'gcc-11' ) }}:
              GCC 11: { CXX: g++-11, TOOLSET: gcc-11, CONTAINER: "linux_gcc11" }
            ${{ if containsValue( parameters.toolsets, 'gcc-10' ) }}:
              GCC 10: { CXX: g++-10, TOOLSET: gcc-10, CONTAINER: "linux_gcc10" }
            ${{ if containsValue( parameters.toolsets, 'gcc-9' ) }}:
              GCC 9: { CXX: g++-9, TOOLSET: gcc-9, CONTAINER: "linux_gcc9" }
            ${{ if containsValue( parameters.toolsets, 'gcc-8' ) }}:
              GCC 8: { CXX: g++-8, TOOLSET: gcc-8, CONTAINER: "linux_gcc8" }
            ${{ if containsValue( parameters.toolsets, 'gcc-7' ) }}:
              GCC 7: { CXX: g++-7, TOOLSET: gcc-7, CONTAINER: "linux_gcc7" }
            ${{ if containsValue( parameters.toolsets, 'gcc-6' ) }}:
              GCC 6: { CXX: g++-6, TOOLSET: gcc-6, CONTAINER: "linux_gcc6" }
            ${{ if containsValue( parameters.toolsets, 'gcc-5' ) }}:
              GCC 5: { CXX: g++-5, TOOLSET: gcc-5, CONTAINER: "linux_gcc5" }
            ${{ if containsValue( parameters.toolsets, 'gcc-4.9' ) }}:
              GCC 4.9: { CXX: g++-4.9, TOOLSET: gcc-4.9, CONTAINER: "linux_gcc49" }
            ${{ if containsValue( parameters.toolsets, 'gcc-4.8' ) }}:
              GCC 4.8: { CXX: g++-4.8, TOOLSET: gcc-4.8, CONTAINER: "linux_gcc48" }
            ${{ if containsValue( parameters.toolsets, 'clang-23' ) }}:
              Clang 23: { CXX: clang++-23, TOOLSET: clang-23, CONTAINER: "linux_clang23" }
            ${{ if containsValue( parameters.toolsets, 'clang-22' ) }}:
              Clang 22: { CXX: clang++-22, TOOLSET: clang-22, CONTAINER: "linux_clang22" }
            ${{ if containsValue( parameters.toolsets, 'clang-21' ) }}:
              Clang 21: { CXX: clang++-21, TOOLSET: clang-21, CONTAINER: "linux_clang21" }
            ${{ if containsValue( parameters.toolsets, 'clang-20' ) }}:
              Clang 20: { CXX: clang++-20, TOOLSET: clang-20, CONTAINER: "linux_clang20" }
            ${{ if containsValue( parameters.toolsets, 'clang-19' ) }}:
              Clang 19: { CXX: clang++-19, TOOLSET: clang-19, CONTAINER: "linux_clang19" }
            ${{ if containsValue( parameters.toolsets, 'clang-18' ) }}:
              Clang 18: { CXX: clang++-18, TOOLSET: clang-18, CONTAINER: "linux_clang18" }
            ${{ if containsValue( parameters.toolsets, 'clang-17' ) }}:
              Clang 17: { CXX: clang++-17, TOOLSET: clang-17, CONTAINER: "linux_clang17" }
            ${{ if containsValue( parameters.toolsets, 'clang-16' ) }}:
              Clang 16: { CXX: clang++-16, TOOLSET: clang-16, CONTAINER: "linux_clang16" }
            ${{ if containsValue( parameters.toolsets, 'clang-15' ) }}:
              Clang 15: { CXX: clang++-15, TOOLSET: clang-15, CONTAINER: "linux_clang15" }
            ${{ if containsValue( parameters.toolsets, 'clang-14' ) }}:
              Clang 14: { CXX: clang++-14, TOOLSET: clang-14, CONTAINER: "linux_clang14" }
            ${{ if containsValue( parameters.toolsets, 'clang-13' ) }}:
              Clang 13: { CXX: clang++-13, TOOLSET: clang-13, CONTAINER: "linux_clang13" }
            ${{ if containsValue( parameters.toolsets, 'clang-12' ) }}:
              Clang 12: { CXX: clang++-12, TOOLSET: clang-12, CONTAINER: "linux_clang12" }
            ${{ if containsValue( parameters.toolsets, 'clang-11' ) }}:
              Clang 11: { CXX: clang++-11, TOOLSET: clang-11, CONTAINER: "linux_clang11" }
            ${{ if containsValue( parameters.toolsets, 'clang-10' ) }}:
              Clang 10: { CXX: clang++-10, TOOLSET: clang-10, CONTAINER: "linux_clang10" }
            ${{ if containsValue( parameters.toolsets, 'clang-9' ) }}:
              Clang 9: { CXX: clang++-9, TOOLSET: clang-9, CONTAINER: "linux_clang9" }
            ${{ if containsValue( parameters.toolsets, 'clang-8' ) }}:
              Clang 8: { CXX: clang++-8, TOOLSET: clang-8, CONTAINER: "linux_clang8" }
            ${{ if containsValue( parameters.toolsets, 'clang-7' ) }}:
              Clang 7: { CXX: clang++-7, TOOLSET: clang-7, CONTAINER: "linux_clang7" }
            ${{ if containsValue( parameters.toolsets, 'clang-6' ) }}:
              Clang 6: { CXX: clang++-6.0, TOOLSET: clang-6.0, CONTAINER: "linux_clang6" }
            ${{ if containsValue( parameters.toolsets, 'clang-5' ) }}:
              Clang 5: { CXX: clang++-5.0, TOOLSET: clang-5.0, CONTAINER: "linux_clang5" }
            ${{ if containsValue( parameters.toolsets, 'clang-4' ) }}:
              Clang 4: { CXX: clang++-4.0, TOOLSET: clang-4.0, CONTAINER: "linux_clang4" }
            ${{ if containsValue( parameters.toolsets, 'clang-3.9' ) }}:
              Clang 3.9: { CXX: clang++-3.9, TOOLSET: clang-3.9, CONTAINER: "linux_clang39" }
        pool:
          vmImage: "ubuntu-latest"
        container: $[ variables['CONTAINER'] ]
        steps:
          - task: CmdLine@2
            displayName: Sudorize
            target: host
            inputs:
              script: |
                /usr/bin/docker exec -t -u root container mv /etc/sudoers /etc/sudoers.bak
                /usr/bin/docker exec -t -u root container apt-get -qq update
                /usr/bin/docker exec -t -u root container apt-get -qq install sudo
                /usr/bin/docker exec -t -u root container mv /etc/sudoers.bak /etc/sudoers
          - bash: |
              APT_OPT="-o Acquire::Retries=3 -yq"
              sudo apt-get ${APT_OPT} update
              sudo apt-get ${APT_OPT} install wget software-properties-common ${{ parameters.apt_packages }}
            displayName: "Install Packages"
          - bash: |
              set -e
              pushd ${HOME}
              wget -nv https://github.com/bfgroup/b2/archive/release.tar.gz
              tar -zxf release.tar.gz
              cd b2-release
              ./bootstrap.sh --cxx=${CXX} ${TOOLSET}
              CXX_PATH=`which ${CXX}`
              echo "using ${TOOLSET%%-[0-9]*} : : ${CXX} ;" > ${HOME}/user-config.jam
              sudo ./b2 --debug-configuration "--user-config=${HOME}/user-config.jam" install ${TOOLSET:+toolset=$TOOLSET}
              popd
            displayName: "Install B2"
          - ${{ each b2_test in parameters.b2_tests }}:
              - bash: |
                  set -e
                  pushd "${{ b2_test.dir }}"
                  b2 "--user-config=${HOME}/user-config.jam" ${TOOLSET:+toolset=$TOOLSET} ${{ b2_test.args }}
                  popd
                displayName: "${{ b2_test.name }}"
      - job: "macOS"
        strategy:
          matrix:
            ${{ if containsValue( parameters.toolsets, 'clang-darwin-26.0' ) }}:
              Xcode 26.0.1:
                {
                  CXX: clang++-,
                  TOOLSET: clang,
                  XCODE_APP: /Applications/Xcode_26.0.1.app,
                  VM_IMAGE: "macOS-15",
                }
            ${{ if containsValue( parameters.toolsets, 'clang-darwin-16.4' ) }}:
              Xcode 16.4:
                {
                  TOOLSET: clang,
                  CXX: clang++,
                  XCODE_APP: /Applications/Xcode_16.4.app,
                  VM_IMAGE: "macOS-15",
                }
            ${{ if containsValue( parameters.toolsets, 'clang-darwin-15.4' ) }}:
              Xcode 15.4:
                {
                  TOOLSET: clang,
                  CXX: clang++,
                  XCODE_APP: /Applications/Xcode_15.4.app,
                  VM_IMAGE: "macOS-14",
                }
        pool:
          vmImage: $(VM_IMAGE)
        steps:
          - bash: |
              set -e
              uname -a
              sudo xcode-select -switch ${XCODE_APP}
              which clang++
              clang++ --version
            displayName: "Install CXX"
          - bash: |
              set -e
              pushd ${HOME}
              wget -nv https://github.com/bfgroup/b2/archive/release.tar.gz
              tar -zxf release.tar.gz
              cd b2-release
              CXX= ./bootstrap.sh
              sudo ./b2 install
              popd
            displayName: "Install B2"
          - ${{ each b2_test in parameters.b2_tests }}:
              - bash: |
                  set -e
                  CXX_PATH=`which ${CXX}`
                  echo "using ${TOOLSET} : : ${CXX_PATH} ;" > ${HOME}/user-config.jam
                  pushd "${{ b2_test.dir }}"
                  b2 "--user-config=${HOME}/user-config.jam" ${TOOLSET:+toolset=$TOOLSET} ${{ b2_test.args }}
                  popd
                displayName: "${{ b2_test.name }}"
      - job: "Windows"
        strategy:
          matrix:
            ${{ if containsValue( parameters.toolsets, 'msvc-14.5' ) }}:
              VS 2025:
                TOOLSET: msvc
                TOOLSET_VERSION: 14.5
                VM_IMAGE: "windows-2025-vs2026"
            ${{ if containsValue( parameters.toolsets, 'msvc-14.3' ) }}:
              VS 2022:
                TOOLSET: msvc
                TOOLSET_VERSION: 14.3
                VM_IMAGE: "windows-2022"
        pool:
          vmImage: $(VM_IMAGE)
        steps:
          - script: |
              cd %BUILD_SOURCESDIRECTORY%/..
              curl "https://github.com/bfgroup/b2/archive/release.zip" -L -o b2.zip
            displayName: Download B2
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: $(Build.SourcesDirectory)/../b2.zip
              destinationFolder: $(Build.SourcesDirectory)/..
              cleanDestinationFolder: false
            displayName: Extract B2
          - script: |
              echo using %TOOLSET% ^: %TOOLSET_VERSION% ^; > %HOMEDRIVE%%HOMEPATH%/user-config.jam
              cd %BUILD_SOURCESDIRECTORY%/../b2-release
              cmd.exe /c bootstrap.bat
            displayName: Install B2
          - ${{ each b2_test in parameters.b2_tests }}:
              - bash: |
                  set BOOST_BUILD_PATH=%BUILD_SOURCESDIRECTORY%/../b2-release
                  cd "%BUILD_SOURCESDIRECTORY%/${{ b2_test.dir }}"
                  %BUILD_SOURCESDIRECTORY%/../b2-release/b2.exe toolset=%TOOLSET% ${{ b2_test.args }}
                displayName: "${{ b2_test.name }}"
